apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  public.pem: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuP5gtequln/5vgEsM2GF
    sK65TJfv0qgxnNWEbyHwmTeavpudmkQU71TzmQD6RkBy2BnHLa2ET2Su4IJUc4IX
    xscTM/ahIcl+liLX7bKOM3fkGMylK7N8q7sz2hRpdzeDpO9tvYwNCvFihWUI8wRO
    vfMGwgS9YjoXr/yBItzHzEO+FSYLDVxdSQF4UhMtbhQJ5VYf2lZy4LCb7j2S2fTy
    G0DhAGjPMsAeDA8gwF78AVivWCCCsK+GKg8ttNMpS8795Bu2+LCJNrCE7sGeY2Ti
    lx2V6xsyGK8+66gDGCEMemjEBverwoFE22Klf9AiUYwKBKlxVFosvMIhDBTqed92
    /wIDAQAB
    -----END PUBLIC KEY-----