apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
stringData:
  DB_PASSWORD: "123456"  
  DB_USERNAME: "postgres"
  USER_SERVICE_API_KEY: "internal-auth-key-12345"
  SPRING_PROFILES_ACTIVE: "kubernetes"