# Build stage
FROM maven:3.9.9-amazoncorretto-23 AS build
WORKDIR /app

# COPY pom.xml & download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline -B

# COPY src & build application
COPY src ./src
RUN mvn clean package -DskipTests

# Runtime stage
FROM amazoncorretto:23-alpine-jdk
WORKDIR /app

# COPY JAR from build stage
COPY --from=build /app/target/*.jar app.jar

# Create non-root user for security
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

# Open port
EXPOSE 8080

# Run application with docker-profiles
ENTRYPOINT ["java", "-jar", "/app/app.jar", "--spring.profiles.active=docker"]