sonar.projectKey=user-service
sonar.projectName=User Service
sonar.projectVersion=0.0.1-SNAPSHOT
sonar.host.url=https://sonarcloud.io
sonar.organization=User Service

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

sonar.junit.reportsPath=target/surefire-reports
sonar.jacoco.reportsPath=target/jacoco.exec
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.java.source=21
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true

sonar.exclusions=**/generated-**,**/target/**,**/test/**
sonar.coverage.exclusions=**/dto/**,**/entity/**,**/config/**,**/exception/**,**/mapper/**,**/specification/**

sonar.language=java